### ISSUE TITLE
Widgets should not show error messages

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-video#205]
As per this bug: https://github.com/Rise-Vision/rise-launcher-electron/issues/700, the Image and Video Widgets should not show error message when files cannot be played.

**Comment by sheadarlison** [comment]
Will fix when we improve Video Widget

**Comment by sheadarlison** [comment]
Closing this issue and https://github.com/Rise-Vision/widget-image/issues/143 because we've opened https://github.com/Rise-Vision/widget-video/issues/227 instead which is more closely aligned with our definition: https://help.risevision.com/hc/en-us/articles/360000805006-Zero-Defect-Escalated-Issue-Policy#what-we-consider-defect

Thanks
