### ISSUE TITLE
Video goes blank erratically when cycling through placeholder.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-video#29]
Steps to reproduce:
1. Add multiple HTML5 Video Widgets with .webm videos to a placeholder
2. Enable PUD, Autoplay, and Scale to fit
3. Play presentation on a display

Result:
Eventually the video placeholder will go black (or the color of the background set in the video widget), while continuing to play audio. This will persist until a player restart is initiated. Time to take effect varies, between 30-120 minutes.

How it should work:
Videos should never go blank, the placeholder should continue to play videos.

Link to Presentation:
http://preview.risevision.com/Viewer.html?type=presentation&id=bfd0a7a6-397f-4ccd-b0bd-6738f90f16fd

OS:
ChromeOS, Windows, Linux

Chrome Ver:
41.0.2272.89 (CAP)

**Comment by stulees** [comment]
@alanclayton @btfrise What is the status of this bug - https://github.com/Rise-Vision/viewer/issues/30 ?

**Comment by alanclayton** [comment]
@stulees doesn't look like anything was done with it. Are you saying that is the cause if this issue?

**Comment by stulees** [comment]
@alanclayton It's not a direct cause of the issue, but it's going to have a significant impact on the Display when a presentation has finished showing in a schedule and the presentation contains a Video Widget(s) because that video content will persist. This will be even more so for Video Folder Widget (work in progress). That bug is preventing us from properly destroying widget content in a widget that requires sending a Done command.

**Comment by alanclayton** [comment]
@stulees okay so do we need to address that before you do anything with this?

**Comment by stulees** [comment]
@alanclayton I think we are okay for now to fix this current Video Widget issue first. I think we need to address the Viewer bug before Video Folder Widget gets added to the store though. Thanks

**Comment by alanclayton** [comment]
@btfrise is this issue still relevant?

**Comment by btfrise** [comment]
This is no longer relevant. I'm closing this bug.

FYI @alanclayton
